version: '3'
 
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py rqworker day &
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
